package com.bankplatform.transfer.application.usecase;

public final class TransferCommands {

    private TransferCommands() {}

    /**
     * Command to initiate a transfer.
     *
     * idempotencyKey is generated by the CLIENT and sent in the request.
     * If the same key is sent again, the cached result is returned
     * without executing the transfer again.
     *
     * transactionPin is the user's 4-6 digit PIN, verified before
     * any money movement. Never stored, used once and discarded.
     */
    public record InitiateTransferCommand(
            String idempotencyKey,
            String sourceAccountNumber,
            String destinationAccountNumber,
            String destinationBankCode,
            long   amountKobo,
            String currency,
            String narration,
            String transactionPin,           // verified, then discarded
            String initiatedByUserId
    ) {}
}